# Question 1 :

Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

### Solution

In [3]:
list = []
for x in range (2000,3200):
    if (x%7==0) and (x%5==0):
        list.append(x)
print(list)

[2030, 2065, 2100, 2135, 2170, 2205, 2240, 2275, 2310, 2345, 2380, 2415, 2450, 2485, 2520, 2555, 2590, 2625, 2660, 2695, 2730, 2765, 2800, 2835, 2870, 2905, 2940, 2975, 3010, 3045, 3080, 3115, 3150, 3185]


# Question 2 :

Write a program that can compute the factorial of a given number. (the factorial of n is the product of all positive integers less than or equal to n).

### Solution

In [6]:
num = int(input("Enter a number: "))    
factorial = 1    
if num < 0:    
    print("Factoriel doesn't exist for negative numbers")    
elif num == 0:    
    print("The factorial of 0 is 1")    
else:    
    for i in range(1,num + 1):    
        factorial = factorial*i    
print("The factorial of",num,"is",factorial)  

Enter a number: 5
The factorial of 5 is 120


# Question 3 :

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

In [1]:
n = int(input("enter a nuber:"))
dict = {i:i**2 for i in range (1,n+1)}
print(dict)

enter a nuber:8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# Question 4 :

Given a non-empty string and an int n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

### solution

In [2]:
def missing_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
noun = input("enter a word : ")
print(missing_char(noun, 1))
print(missing_char(noun, 0))
print(missing_char(noun, 4))

enter a word : kitten
ktten
itten
kittn


# Question 5 :

Write a NumPy program to convert a NumPy array into a Python list structure.

Expected Output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 

### solution

In [3]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# Question 6 :

Write a NumPy program to compute the covariance matrix of two given arrays. 

### solution 

In [5]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([2, 1, 0])
print("\nOriginal array1:")
print(a)
print("\nOriginal array1:")
print(b)
print("\nCovariance matrix of the said arrays:\n",np.cov(a, b))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


# ex 7:

Question: Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (that means D contains more than value)

Example Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

Hints: If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26) In case of input data being supplied to the question, it should be assumed to be a console input. 

### solution

In [4]:
numbers = input("give D: ")
numbers = numbers.split(',')
import numpy as np
result = []
#result is a list 
for D in numbers:
    Q = round(np.sqrt(2 * 50 * int(D) / 30))
    result.append(Q)

print(result)

give D: 2
[3]
